### ISSUE TITLE
Looking forward to the train/test instructions

### ISSUE THREAD

**Issue by olga-zats** [Evm7/ego4dlta-icvae#1]
Hi!

Your work seems very interesting! I wondered if you will make the train and test instructions available soon? Thank you!

Best,
Olga

**Comment by Evm7** [comment]
Hi Olga! I have been working on a paper submission of this work. In the near future I will add detailed instructions to facilitate the reproduction of the results. Still, the procedure for training/testing is simillar than the Ego4D LTA scripts provided, as I based this code in that.
