### ISSUE TITLE
`taxonomy_clip_embeddings.pt` missing

### ISSUE THREAD

**Issue by Tushar-N** [Evm7/ego4dlta-icvae#3]
Could you point me to the script to generate `taxonomy_clip_embeddings.pt`? I can't find it in the repo.

**Comment by Evm7** [comment]
taxonomy_clip_embeddings.pt is a dictionary that maps verbs and noun classes into their CLIP features. To generate this file, you can simply make use of CLIP text_encoder function for each verb and noun.
I have added the taxonomy_clip_embeddings file to the model.

However, this file was only used during the experiments, and it is not used in the final model.
